version: 2

models:
  - name: fact_ecoenergy_data
    description: >
      The transformed dataset provides a comprehensive inventory of individual power plants 
      in Germany and offers detailed insights into the country's renewable energy infrastructure 
      after removing sparse data, performing data cleaning, and applying transformations.
    columns:
      - name: electrical_capacity
        description: Installed electrical capacity in MW.
      - name: energy_source_level_1
        description: Type of energy source (e.g., Renewable energy).
        tests: 
            - accepted_values:
                values: "{{ var('energy_source_level_1') }}"
                severity: warn
      - name: energy_source_level_2
        description: Type of energy source (e.g., Wind, Solar).
        tests: 
            - accepted_values:
                values: "{{ var('energy_source_level_2') }}"
                severity: warn
      - name: energy_source_level_3
        description: Subtype of energy source (e.g., Biomass and biogas).
        tests: 
            - accepted_values:
                values: "{{ var('energy_source_level_2') }}"
                severity: warn
      - name: technology
        description: Technology to harvest energy source (e.g., Onshore, Photovoltaics).
      - name: data_source
        description: Source of database entry.
      - name: nuts_1_region
        description: Code of the NUTS 1 region the facility is in (e.g., DE1).
      - name: nuts_2_region
        description: Code of the NUTS 2 region the facility is in (e.g., DE11).
      - name: nuts_3_region
        description: Code of the NUTS 3 region the facility is in (e.g., DE111).
      - name: lon
        description: Longitude coordinates.
      - name: lat
        description: Latitude coordinates.
      - name: municipality
        description: Name of German Gemeinde (municipality).
      - name: postcode
        description: German zip code.
      - name: address
        description: Street name or name of land parcel.
      - name: federal_state
        description: Name of German administrative level 'Bundesland'.
      - name: commissioning_date
        description: Date of commissioning of specific unit.
      - name: decommissioning_date
        description: Date of decommissioning of specific unit.
      - name: voltage_level
        description: Voltage level of grid connection.
      - name: dso
        description: Name of distribution system operator of the region.
      - name: tso
        description: Name of transmission system operator of the area.