version: '3'
services:
  ecoenergy_de:
    image: mageai/mageai:0.9.65
    container_name: ecoenergy_de
    command: mage start mage-ecoenergy
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/ecoenergy-germany
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5