# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_ecoenergy'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_ecoenergy'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this config, we tell dbt to build all models in the models/.../

models:
  dbt_ecoenergy:
      # Applies to all files under models/.../
      staging:
          materialized: view
      core:
          materialized: table
vars:
  energy_source_level_1: ["Renewable energy"]
  energy_source_level_2: ["Bioenergy", "Geothermal", "Hydro", "Wind", "Solar"]
  energy_source_level_3: ["Biomass and biogas", "Sewage and landfill gas", null]